name: "Setup Node.js and Dependencies"
description: "Common setup steps for Node.js projects with caching"

inputs:
  cache-key-suffix:
    description: "Suffix to append to cache key for job-specific caching"
    required: false
    default: "default"

  additional-cache-paths:
    description: "Additional paths to include in cache (newline separated)"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether there was a cache hit"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"

    - name: Cache dependencies and build outputs
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          node_modules
          ~/.npm
          ~/.cache/npm
          .eslintcache
          ${{ inputs.additional-cache-paths }}
        key: ${{ runner.os }}-vite-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('src/**/*.[jt]s?(x)', 'vite.config.*') }}
        restore-keys: |
          ${{ runner.os }}-vite-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/package-lock.json') }}-
          ${{ runner.os }}-vite-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-vite-

    - name: Report cache status
      shell: bash
      run: |
        if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Cache hit - dependencies restored from cache"
        else
          echo "❌ Cache miss - will install fresh dependencies"
        fi

    - name: Install dependencies
      shell: bash
      run: npm ci
